n = input('digite algo para saber algumas informações!')
print('LEMBRANDO:TRUE É (VERDADEIRO) = SIM ' )
print('                 E ')
print('FALSE É (FALSO) = NÃO!')
print('A CLASSE PRIMITIVA É')
print('O TIPO PRIMITIVO', type(n))
print(' é alfanumerico?', n.isalnum())
print(' é uma letra?', n.isalpha())
print(' é um numero?', n.isnumeric())
print('é um digito?', n.isdigit())
print('Ele está identificado?', n.isidentifier())
print('é uma letra minuscula?', n.islower())
print('é uma letra maiuscula?', n.isupper())
print('é um numero decimal?', n.isdecimal())
print('ela tem letras minusculas e maiusculas?', n.istitle())

