print('------------------------------------------')
print(' cauculadora de salário 15% de aumento!  ')
print('------------------------------------------')
s = float(input(' digite aqui o seu salário atual : '))
print('------------------------------------------')
print ('O seu salário com um aumento de 15% é\n {:.2f}'.format(s+(s*15)/100))