print('='*70)
nome = str(input('digite o seu nome completo: ')).strip()
print('O seu nome em maiúsculo é:')
print(nome.upper())
print('O seu nome em minúsculo é:')
print(nome.lower())
print('NO seu nome existe {}  caracteres'.format(len(nome) - nome.count(' ')))
divido = nome.split()
print('E no primeiro nome existem:')
print((len(divido[0])), end='')
print(' caracteres')
print('E no primeiro nome existem: {}'.format(nome.find(' ')))
