print('------------------------------------------')
print('Calculadora de área: da parede e o necessario para ser pintada!')
print('Cada litro de tinta pinta 2mX2m')
print('------------------------------------------')
l = float(input('Digite a largura ='))
a = float(input('Digite aqui a altura ='))
print('------------------------------------------')
print('O valor total da área é {}m² Metros'.format (l*a))
print('e será necessario {} litros de tinta para pintala'.format((l*a)/2))
print('------------------------------------------')
